services:
  database:
    image: mongo:latest
    container_name: mongodb_green-and-coop
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  forecast:
    build: .
    env_file: .env
    depends_on:
      - database
    volumes:
      - forecast_data:/app/ready_for_mongo
    command: sh -c "python s3_staging.py && python ingest_to_mongo.py"

volumes:
  mongo_data:
  forecast_data:
